package definitions

// Boundaries ...
type Boundaries struct{}

// TBoundaries ...
type TBoundaries struct{}

/*
 * @Elementary
 */

// CancelEventDefinition ...
type CancelEventDefinition struct{}

// TCancelEventDefinition ...
type TCancelEventDefinition struct{}

// CompensateEventDefinition ...
type CompensateEventDefinition struct{}

// TCompensateEventDefinition ...
type TCompensateEventDefinition struct{}

// ConditionalEventDefinition ...
type ConditionalEventDefinition struct {
	CamundaVariableName string `xml:"camunda:variableName" json:"variableName,omitempty"`
}

// TConditionalEventDefinition ...
type TConditionalEventDefinition struct {
	CamundaVariableName string `xml:"variableName" json:"variableName,omitempty"`
}

// EndEvent ...
type EndEvent struct{}

// TEndEvent ...
type TEndEvent struct{}

// ErrorEventDefinition ...
type ErrorEventDefinition struct{}

// TErrorEventDefinition ...
type TErrorEventDefinition struct{}

// EscalationEventDefinition ...
type EscalationEventDefinition struct{}

// EscalationEventDefinition ...
type TEscalationEventDefinition struct{}

// IntermediateCatchEvent ...
type IntermediateCatchEvent struct{}

// TIntermediateCatchEvent ...
type TIntermediateCatchEvent struct{}

// IntermediateThrowEvent ...
type IntermediateThrowEvent struct{}

// TIntermediateThrowEvent ...
type TIntermediateThrowEvent struct{}

// LinkEventDefinition ...
type LinkEventDefinition struct{}

// TLinkEventDefinition ...
type TLinkEventDefinition struct{}

// MessageEventDefinition ...
type MessageEventDefinition struct{}

// TMessageEventDefinition ...
type TMessageEventDefinition struct{}

// SignalEventDefinition ...
type SignalEventDefinition struct{}

// TSignalEventDefinition ...
type TSignalEventDefinition struct{}

// StartEvent ...
type StartEvent struct{}

// TStartEvent ...
type TStartEvent struct{}

// TerminateEventDefinition ...
type TerminateEventDefinition struct{}

// TTerminateEventDefinition ...
type TTerminateEventDefinition struct{}

// TimerEventDefinition ...
type TimerEventDefinition struct{}

// TTimerEventDefinition ...
type TTimerEventDefinition struct{}
